spring:
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@10.211.55.3:1521/orcl
    username: c##chan
    password: gurcks258
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 200000
      max-lifetime: 240000
      pool-name: oraPool
  thymeleaf:
    enabled: true
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

mybatis:
  # alias 설정을 사용할 수 있는 경로 설정
  type-aliases-package: com.rg.nllp
  # resources 디렉토리 하위의 mapper 파일 경로
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    # 언더바에서 카멜케이스로 변환하여 결과값 전달
    map-underscore-to-camel-case: true
    # mybatis 변수 #{xxx} null 허용
    jdbc-type-for-null: varchar






