
### 로그인
POST http://localhost:8080/user/findUserInfo HTTP/1.1
content-type: application/json; charset=UTF-8

{
    "sgbCd" : "3550000",
    "userId" : "user0001",
    "userPw" : "1234"
}
### 사용자신청
POST http://localhost:8080/user/instUserReqInfo HTTP/1.1
content-type: application/json; charset=UTF-8

{
    "sgbCd" : "3550000",
    "userId" : "user0001",
    "userPw" : "1234",
    "userNm" : "김길동"
}
### 사용자신청 허가
POST http://localhost:8080/user/instUserInfo HTTP/1.1
content-type: application/json; charset=UTF-8

{
    "sgbCd" : "3550000",
    "userId" : "user0001"
}